export const sagaActions = {
    FETCH_IMAGES: 'FETCH_IMAGES',
    FETCH_TOPICS: 'FETCH_TOPICS',
    FETCH_IMAGES_BY_TOPIC: 'FETCH_IMAGES_BY_TOPIC',
    FETCH_IMAGES_SEARCH: 'FETCH_IMAGES_SEARCH',
  }